---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: licenses, licensing, subscriptions, annual subscription, paygo, hourly subscription 
summary: Há duas maneiras de pagar pelas relações de sincronização após o término da avaliação gratuita de 14 dias. A primeira opção é se inscrever na AWS ou no Azure para pagar conforme o uso ou pagar anualmente. A segunda opção é comprar licenças diretamente da NetApp. 
---
= Visão geral do licenciamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há duas maneiras de pagar pelas relações de sincronização após o término da avaliação gratuita de 14 dias. A primeira opção é se inscrever na AWS ou no Azure para pagar conforme o uso ou pagar anualmente. A segunda opção é comprar licenças diretamente da NetApp.

As licenças devem ser gerenciadas por meio da cópia e sincronização do BlueXP  ou do site aplicável e *não* por meio de uma carteira digital.



== Subscrição do mercado

A subscrição do serviço de cópia e sincronização do BlueXP  da AWS ou do Azure permite que você pague por hora ou pague anualmente. link:task-licensing.html["Você pode se inscrever na AWS ou no Azure"], dependendo de onde você deseja ser cobrado.



=== Subscrição por hora

Com uma assinatura paga conforme o uso por hora, você é cobrado por hora com base no número de relacionamentos de sincronização criados.

* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Ver preços no Azure"^]
* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["Veja a definição de preço para pagamento conforme o uso na AWS"^]




=== Assinatura anual

Uma assinatura anual fornece uma licença para 20 relacionamentos de sincronização que você paga antecipadamente. Se você passar acima de 20 relacionamentos de sincronização e se inscreveu através da AWS, você pagará pelas relações adicionais por hora.

https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Veja os preços anuais na AWS"^]



== Licenças da NetApp

Outra forma de pagar antecipadamente pelas relações de sincronização é comprando licenças diretamente da NetApp. Cada licença permite criar até 20 relações de sincronização.

Você pode usar essas licenças com uma assinatura da AWS ou do Azure. Por exemplo, se você tiver 25 relacionamentos de sincronização, poderá pagar pelas primeiras 20 relações de sincronização usando uma licença e pagar conforme o uso da AWS ou do Azure com as 5 relações de sincronização restantes.

link:task-licensing.html["Saiba como comprar licenças e adicioná-las à cópia e sincronização do BlueXP "].



=== Termos da licença

Os clientes que comprarem um BYOL (traga sua própria licença) para o serviço de cópia e sincronização do BlueXP  devem estar cientes das limitações associadas ao direito de licença.

* Os clientes têm o direito de utilizar a licença BYOL por um prazo não superior a um ano a partir da data de entrega.
* Os clientes têm o direito de utilizar a licença BYOL para estabelecer e não exceder um total de 20 conexões individuais entre uma fonte e um destino (cada uma uma uma "relação de sincronização").
* O direito de um cliente expira na conclusão do prazo de licença de um ano, independentemente de o Cliente ter atingido a limitação de relação de sincronização de 20.
* No caso de o Cliente optar por renovar a sua licença, as relações de sincronização não utilizadas associadas à concessão de licença anterior NÃO serão transferidas para a renovação da licença.

