---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: Você pode obter ajuda com a cópia e sincronização do BlueXP  e encontrar mais informações através de vários recursos, incluindo fóruns, serviços de bate-papo e vídeos. 
---
= Perguntas frequentes técnicas de cópia e sincronização do BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esta FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== Como começar

As perguntas a seguir estão relacionadas a como começar a usar a cópia e sincronização do BlueXP .



=== Como funciona a cópia e sincronização do BlueXP ?

A cópia e sincronização do BlueXP  usa o software de corretor de dados do NetApp para sincronizar dados de uma origem para um destino (isso é chamado de _relação de sincronização_).

Um grupo de corretores de dados controla as relações de sincronização entre suas fontes e destinos. Depois de configurar uma relação de sincronização, o BlueXP  copy and Sync analisa o sistema de origem e o divide em vários fluxos de replicação para enviar para os dados de destino selecionados.

Após a cópia inicial, o serviço sincroniza todos os dados alterados com base na programação definida.



=== Como funciona o teste gratuito de 14 dias?

A avaliação gratuita de 14 dias começa quando você se inscreve no serviço de cópia e sincronização do BlueXP . Você não está sujeito a cobranças do NetApp por relações de cópia e sincronização do BlueXP  criadas por 14 dias. No entanto, todas as cobranças de recursos para quaisquer corretores de dados que você implantar ainda se aplicam.



=== Quanto custa a cópia e sincronização do BlueXP ?

Há dois tipos de custos associados ao uso de cópia e sincronização do BlueXP : Taxas de serviço e taxas de recursos.

*Taxas de serviço*

Para preços de pagamento conforme o uso, as taxas de serviço de cópia e sincronização do BlueXP  são por hora, com base no número de relacionamentos de sincronização criados.

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["Veja a definição de preço para pagamento conforme o uso na AWS"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Veja os preços anuais na AWS"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Ver preços no Azure"^]


As licenças de cópia e sincronização do BlueXP  também estão disponíveis através do seu representante da NetApp. Cada licença permite 20 relações de sincronização por 12 meses.

link:concept-licensing.html["Saiba mais sobre licenças"].


NOTE: As relações de cópia e sincronização do BlueXP  são gratuitas para Cloud Volumes Service e Azure NetApp Files.

*Cobranças de recursos*

As cobranças por recursos estão relacionadas aos custos de computação e storage para executar o agente de dados na nuvem.



=== Como é que a cópia e a sincronização do BlueXP  são faturadas e como faço para gerenciar minha assinatura?

Há duas maneiras de pagar pelas relações de sincronização após o término da avaliação gratuita de 14 dias. A primeira opção é se inscrever na AWS ou no Azure, o que permite que você pague conforme o uso ou pague anualmente. A segunda opção é comprar licenças diretamente da NetApp. Em cada caso, a sua subscrição será gerida através do mercado do fornecedor e *não* através da interface de utilizador de cópia e sincronização do BlueXP .



=== Posso usar a cópia e a sincronização do BlueXP  fora da nuvem?

Sim, você pode usar a cópia e a sincronização do BlueXP  em uma arquitetura que não seja na nuvem. A origem e o destino podem residir no local, assim como o software do agente de dados.

Observe os seguintes pontos-chave sobre o uso de cópia e sincronização do BlueXP  fora da nuvem:

* Um grupo de corretores de dados precisa de uma conexão com a Internet para se comunicar com o serviço de cópia e sincronização do BlueXP .
* Se você não comprar uma licença diretamente da NetApp, precisará de uma conta da AWS ou do Azure para a cobrança do serviço de cópia e sincronização do PAYGO BlueXP .




=== Como faço para acessar a cópia e sincronização do BlueXP ?

A cópia e sincronização do BlueXP  estão disponíveis no site do BlueXP  na guia *Sincronizar*.



=== O que é um grupo de corretores de dados?

Cada agente de dados pertence a um grupo de corretores de dados. Agrupar os corretores de dados em conjunto ajuda a melhorar o desempenho das relações de sincronização.



== Fontes e alvos suportados

As perguntas a seguir relacionadas à origem e aos destinos que são suportados em um relacionamento de sincronização.



=== Quais fontes e destinos o BlueXP  copia e sincroniza suporte?

A cópia e sincronização do BlueXP  suporta vários tipos diferentes de relações de sincronização. link:reference-supported-relationships.html["Veja a lista inteira"].



=== Quais versões do NFS e SMB o BlueXP  copia e sincroniza?

A cópia e sincronização do BlueXP  são compatíveis com a versão 3 e posterior do NFS e com a versão 1 e posterior do SMB.

link:reference-requirements.html["Saiba mais sobre os requisitos de sincronização"].



=== Quando o Amazon S3 é o destino, os dados podem ser dispostos em camadas em uma classe de armazenamento S3 específica?

Sim, você pode escolher uma classe de armazenamento S3 específica quando o AWS S3 for o destino:

* Standard (esta é a classe padrão)
* Disposição em camadas inteligente
* Acesso padrão-infrequente
* Uma zona de acesso pouco frequente
* Glacier Deep Archive
* Recuperação flexível do Glacier
* Recuperação instantânea do Glacier




=== E quanto às camadas de storage do Azure Blob?

Você pode escolher uma categoria de storage específica do Azure Blob quando um contêiner de Blob é o destino:

* Armazenamento a quente
* Armazenamento frio




=== Você é compatível com categorias de storage do Google Cloud?

Sim, você pode escolher uma classe de storage específica quando um bucket do Google Cloud Storage for o destino:

* Padrão
* Nearline
* Coldline
* Arquivar




== Rede

As perguntas a seguir estão relacionadas aos requisitos de rede para cópia e sincronização do BlueXP .



=== Quais são os requisitos de rede para cópia e sincronização do BlueXP ?

O ambiente de cópia e sincronização do BlueXP  exige que um grupo de corretores de dados seja conetado à origem e ao destino por meio do protocolo selecionado ou da API de storage de objetos (Amazon S3, Azure Blob, IBM Cloud Object Storage).

Além disso, um grupo de corretores de dados precisa de uma conexão de saída de Internet pela porta 443 para que ele possa se comunicar com o serviço de cópia e sincronização do BlueXP  e entrar em Contato com alguns outros serviços e repositórios.

Para mais detalhes, link:reference-networking.html["rever os requisitos de rede"].



=== Posso usar um servidor proxy com o corretor de dados?

Sim.

A cópia e sincronização do BlueXP  suporta servidores proxy com ou sem autenticação básica. Se você especificar um servidor proxy ao implantar um corretor de dados, todo o tráfego HTTP e HTTPS do corretor de dados será roteado através do proxy. Observe que o tráfego não HTTP, como NFS ou SMB, não pode ser roteado por meio de um servidor proxy.

A única limitação do servidor proxy é ao usar criptografia de dados em trânsito com um relacionamento de sincronização NFS ou Azure NetApp Files. Os dados criptografados são enviados por HTTPS e não são roteáveis por meio de um servidor proxy.



== Sincronização de dados

As perguntas a seguir referem-se a como a sincronização de dados funciona.



=== Com que frequência ocorre a sincronização?

A programação padrão é definida para sincronização diária. Após a sincronização inicial, você pode:

* Modifique a programação de sincronização para o número desejado de dias, horas ou minutos
* Desative a programação de sincronização
* Eliminar a programação de sincronização (nenhum dado será perdido; apenas a relação de sincronização será removida)




=== Qual é a programação mínima de sincronização?

Você pode agendar uma relação para sincronizar dados a cada 1 minutos.



=== O grupo de corretores de dados tenta novamente quando um arquivo não consegue sincronizar? Ou o tempo limite?

Um grupo de corretores de dados não expira quando um único arquivo falha na transferência. Em vez disso, o grupo de corretores de dados tenta novamente 3 vezes antes de pular o arquivo. O valor de repetição é configurável nas definições de uma relação de sincronização.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["Saiba como alterar as configurações de uma relação de sincronização"].



=== E se eu tiver um conjunto de dados muito grande?

Se um único diretório contém 600.000 arquivos ou mais, mailto:ng-cloudsync-support NetApp.com[Contact US] para que possamos ajudá-lo a configurar o grupo de corretores de dados para lidar com a carga útil. Talvez seja necessário adicionar memória adicional ao grupo de corretores de dados.

Note que não há limite para o número total de arquivos no ponto de montagem. A memória extra é necessária para diretórios grandes com arquivos 600.000 ou mais, independentemente do seu nível na hierarquia (diretório superior ou subdiretório).



== Segurança

As seguintes perguntas relacionadas à segurança.



=== A cópia e sincronização do BlueXP  são seguras?

Sim. Toda a conetividade de rede do serviço de cópia e sincronização do BlueXP  é feita usando https://aws.amazon.com/sqs/["Amazon Simple Queue Service (SQS)"^]o .

Todas as comunicações entre o grupo de corretores de dados e o Amazon S3, Azure Blob, Google Cloud Storage e IBM Cloud Object Storage são feitas por meio do protocolo HTTPS.

Se você estiver usando cópia e sincronização do BlueXP  com sistemas locais (de origem ou destino), veja algumas opções de conetividade recomendadas:

* Uma conexão AWS Direct Connect, Azure ExpressRoute ou Google Cloud Interconnect, que não é roteada pela Internet (e só pode se comunicar com as redes de nuvem especificadas)
* Uma conexão VPN entre seu dispositivo de gateway local e suas redes na nuvem
* Para transferência de dados extra segura com buckets do S3, armazenamento de Blobs do Azure ou Google Cloud Storage, é possível estabelecer um endpoint Amazon Private S3, pontos de extremidade de serviço da rede virtual do Azure ou o acesso privado do Google.


Qualquer um desses métodos estabelece uma conexão segura entre seus servidores nas locais e um grupo de corretores de dados de cópia e sincronização do BlueXP .



=== Os dados são criptografados por cópia e sincronização do BlueXP ?

* A cópia e sincronização do BlueXP  são compatíveis com a criptografia de dados em trânsito entre servidores NFS de origem e destino. link:task-nfs-encryption.html["Saiba mais"].
* Para SMB, a cópia e sincronização do BlueXP  suporta dados SMB 3,0 e 3,11 encriptados no lado do servidor. O BlueXP  copia e sincroniza os dados criptografados da origem para o destino onde os dados permanecem criptografados.
+
A cópia e a sincronização do BlueXP  não podem criptografar os dados SMB em si.

* Quando um bucket do Amazon S3 é o destino em uma relação de sincronização, você pode escolher se deseja ativar a criptografia de dados usando a criptografia AWS KMS ou AES-256.
* Quando um intervalo do Google Storage é o destino em uma relação de sincronização, você pode escolher se deseja usar a chave de criptografia padrão gerenciada pelo Google ou sua própria chave KMS.




== Permissões

As perguntas a seguir estão relacionadas às permissões de dados.



=== As permissões de dados SMB são sincronizadas com o local de destino?

É possível configurar a cópia e a sincronização do BlueXP  para preservar listas de controle de acesso (ACLs) entre um compartilhamento SMB de origem e um compartilhamento SMB de destino e de um compartilhamento SMB de origem para o storage de objetos (exceto o ONTAP S3).


NOTE: A cópia e sincronização do BlueXP  não são compatíveis com a cópia de ACLs do storage de objetos para compartilhamentos SMB.

link:task-copying-acls.html["Saiba como copiar ACLs entre compartilhamentos SMB"].



=== As permissões de dados NFS são sincronizadas com o local de destino?

A cópia e sincronização do BlueXP  copia automaticamente as permissões NFS entre servidores NFS da seguinte forma:

* NFS versão 3: Cópia e sincronização do BlueXP  copia as permissões e o proprietário do grupo de usuários.
* NFS versão 4: Cópias BlueXP  de cópia e sincronização das ACLs.




== Metadados de storage de objetos



=== Que tipos de relações de sincronização preservam os metadados do storage de objetos?

O BlueXP  copia e sincroniza os metadados de storage de objetos da origem para o destino para os seguintes tipos de relações de sincronização:

* Amazon S3 -> Amazon S3 1
* Amazon S3 -> StorageGRID
* StorageGRID -> Amazon S3
* StorageGRID -> StorageGRID
* StorageGRID -> Google Cloud Storage
* Google Cloud Storage -> StorageGRID 1
* Google Cloud Storage -> IBM Cloud Object Storage 1
* Google Cloud Storage -> Amazon S3 1
* Amazon S3 -> Google Cloud Storage
* IBM Cloud Object Storage -> Google Cloud Storage
* StorageGRID -> armazenamento de objetos em nuvem da IBM
* IBM Cloud Object Storage -> StorageGRID
* IBM Cloud Object Storage -> IBM Cloud Object Storage


1 para essas relações de sincronização, você precisa link:task-creating-relationships.html["Ative a configuração Copiar para objetos ao criar a relação de sincronização"].



=== Que tipos de metadados são replicados durante sincronizações em que NFS ou SMB são a origem?

Metadados como ID de usuário, tempo de modificação, tempo de acesso e GID são replicados por padrão. Os usuários podem optar por replicar a ACL do CIFS marcando-a conforme necessário ao criar uma relação de sincronização.



== Desempenho

As perguntas a seguir estão relacionadas ao desempenho de cópia e sincronização do BlueXP .



=== O que representa o indicador de progresso de uma relação de sincronização?

A relação de sincronização mostra a taxa de transferência do adaptador de rede do grupo de corretores de dados. Se você acelerou o desempenho de sincronização usando vários corretores de dados, a taxa de transferência será a soma de todo o tráfego. Essa taxa de transferência é atualizada a cada 20 segundos.



=== Estou enfrentando problemas de desempenho. Podemos limitar o número de transferências simultâneas?

Se você tiver arquivos muito grandes (várias Tibs cada), pode levar muito tempo para concluir o processo de transferência e o desempenho pode ser afetado.

Limitar o número de transferências simultâneas pode ajudar. Mailto:ng-cloudsync-support NetApp.com[Contacte-nos para obter ajuda].



=== Por que estou tendo baixo desempenho com o Azure NetApp Files?

Quando você sincroniza dados com ou do Azure NetApp Files, você pode ter falhas e problemas de desempenho se o nível de serviço de disco for padrão.

Altere o nível de serviço para Premium ou Ultra para melhorar o desempenho de sincronização.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Saiba mais sobre os níveis de serviço e a taxa de transferência do Azure NetApp Files"^].



=== Por que estou tendo baixo desempenho com o Cloud Volumes Service para AWS?

Ao sincronizar dados de ou para um volume de nuvem, você pode ter falhas e problemas de desempenho se o nível de performance do volume de nuvem for padrão.

Altere o nível de serviço para Premium ou Extreme para melhorar o desempenho de sincronização.



=== Quantos corretores de dados são necessários em um grupo?

Ao criar um novo relacionamento, você começa com um único agente de dados em um grupo (a menos que você tenha selecionado um agente de dados existente que pertence a um relacionamento de sincronização acelerada). Em muitos casos, um único agente de dados pode atender aos requisitos de desempenho de um relacionamento de sincronização. Se isso não acontecer, você pode acelerar o desempenho de sincronização adicionando corretores de dados adicionais ao grupo. Mas você deve primeiro verificar outros fatores que podem afetar o desempenho da sincronização.

Vários fatores podem afetar o desempenho da transferência de dados. O desempenho geral da sincronização pode ser afetado devido à largura de banda, latência e topologia da rede, bem como às especificações de VM do agente de dados e ao desempenho do sistema de armazenamento. Por exemplo, um único corretor de dados em um grupo pode atingir 100 MB/s, enquanto a taxa de transferência de disco no destino pode permitir apenas 64 MB/s. Como resultado, o grupo de corretores de dados continua tentando copiar os dados, mas o destino não consegue atender ao desempenho do grupo de corretores de dados.

Portanto, certifique-se de verificar o desempenho de sua rede e a taxa de transferência de disco no destino.

Em seguida, você pode considerar acelerar o desempenho de sincronização adicionando um agente de dados adicional a um grupo para compartilhar a carga desse relacionamento. link:task-managing-relationships.html#accelerate-sync-performance["Saiba como acelerar o desempenho de sincronização"].



== Eliminar coisas

As perguntas a seguir referem-se à exclusão de relacionamentos de sincronização e dados de fontes e destinos.



=== O que acontece se eu excluir minha relação de cópia e sincronização do BlueXP ?

A exclusão de um relacionamento interrompe todas as futuras sincronizações de dados e encerra o pagamento. Todos os dados sincronizados com o alvo permanecem no estado em que se encontram.



=== O que acontece se eu excluir algo do meu servidor de origem? É removido do alvo também?

Por padrão, se você tiver uma relação de sincronização ativa, o item excluído no servidor de origem não será excluído do destino durante a próxima sincronização. Mas há uma opção nas configurações de sincronização para cada relacionamento, onde você pode definir que a cópia e sincronização do BlueXP  excluirão arquivos no local de destino se eles foram excluídos da origem.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["Saiba como alterar as configurações de uma relação de sincronização"].



=== O que acontece se eu excluir algo do meu alvo? É removido da minha fonte também?

Se um item for excluído do destino, ele não será removido da origem. O relacionamento é unidirecional, da origem ao destino. No próximo ciclo de sincronização, a cópia e sincronização do BlueXP  compara a origem com o destino, identifica que o item está ausente e a cópia e sincronização do BlueXP  o copiam novamente da origem para o destino.



== Solução de problemas

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["Base de conhecimento da NetApp: Perguntas frequentes sobre cópia e sincronização do BlueXP : Suporte e solução de problemas"^]



== Mergulho profundo do agente de dados

A seguinte pergunta diz respeito ao corretor de dados.



=== Você pode explicar a arquitetura do corretor de dados?

Claro. Aqui estão os pontos mais importantes:

* O corretor de dados é um aplicativo node.js executado em um host Linux.
* A cópia e sincronização do BlueXP  implanta o agente de dados da seguinte forma:
+
** AWS: A partir de um modelo do AWS CloudFormation
** Azure: Do Azure Resource Manager
** Google: Do Google Cloud Deployment Manager
** Se você usa seu próprio host Linux, você precisa instalar manualmente o software


* O software de data broker atualiza-se automaticamente para a versão mais recente.
* O corretor de dados usa o AWS SQS como um canal de comunicação confiável e seguro e para controle e monitoramento. SQS também fornece uma camada de persistência.
* Você pode adicionar corretores de dados adicionais a um grupo para aumentar a velocidade de transferência e adicionar alta disponibilidade. Há resiliência de serviços se um agente de dados falhar.

