---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: Há duas maneiras de pagar pelas relações de sincronização após o término da avaliação gratuita de 14 dias. A primeira opção é pagar conforme o uso. A segunda opção é comprar licenças diretamente da NetApp. 
---
= Pague pelas relações de sincronização após o término da avaliação gratuita
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Há duas maneiras de pagar pelas relações de sincronização após o término da avaliação gratuita de 14 dias. A primeira opção é se inscrever na AWS ou no Azure para pagar conforme o uso ou pagar anualmente. A segunda opção é comprar licenças diretamente da NetApp.

Você pode se inscrever no AWS Marketplace ou no Azure Marketplace. Você não pode se inscrever em ambos.

Você tem a opção de usar licenças do NetApp com uma assinatura do Marketplace. Por exemplo, se você tiver 25 relacionamentos de sincronização, poderá pagar pelas primeiras 20 relações de sincronização usando uma licença e pagar conforme o uso da AWS ou do Azure com as 5 relações de sincronização restantes.

link:concept-licensing.html["Saiba mais sobre como as licenças funcionam"].

Se você não pagar imediatamente após o término da avaliação gratuita, você não será capaz de criar relacionamentos adicionais. Relacionamentos existentes não são excluídos, mas você não pode fazer alterações a eles até que você assine ou insira uma licença.

As licenças devem ser gerenciadas por meio da cópia e sincronização do BlueXP  ou do site aplicável e *não* por meio de uma carteira digital.



== [[AWS]]Inscreva-se na AWS

A AWS permite que você pague conforme o uso ou pague anualmente.

.Passos para pagar conforme o uso
. No menu de navegação BlueXP , selecione *Mobilidade > Copiar e sincronizar*.
. Selecione *Licenciamento*.
. Selecione *AWS*.
. Selecione *Subscribe* e, em seguida, selecione *Continue*.
. Inscreva-se no AWS Marketplace e faça login novamente no serviço de cópia e sincronização do BlueXP  para concluir o Registro.
+
O vídeo a seguir mostra o processo:

+
.Assine a cópia e a sincronização do BlueXP  no AWS Marketplace
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.Passos para pagar anualmente
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Vá para a página do AWS Marketplace"^].
. Selecione *continuar para assinar*.
. Selecione suas opções de contrato e, em seguida, selecione *criar contrato*.




== [[azure]]Inscreva-se no Azure

O Azure permite que você pague conforme o uso ou pague anualmente.

.O que você vai precisar
Uma conta de usuário do Azure que tenha permissões de Colaborador ou proprietário na assinatura relevante.

.Passos
. No menu de navegação BlueXP , selecione *Mobilidade > Copiar e sincronizar*.
. Selecione *Licenciamento*.
. Selecione *Azure*.
. Selecione *Subscribe* e, em seguida, selecione *Continue*.
. No portal do Azure, selecione *criar*, selecione suas opções e, em seguida, selecione *assinar*.
+
Selecione *mensal* para pagar por hora, ou *anual* para pagar por um ano antes.

. Quando a implantação estiver concluída, selecione o nome do recurso SaaS no pop-up de notificação.
. Selecione *Configurar conta* para retornar à cópia e sincronização do BlueXP .
+
O vídeo a seguir mostra o processo:

+
.Assine a cópia e sincronização do BlueXP  a partir do Azure Marketplace
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenças]]Compre licenças do NetApp e adicionando-as à cópia e sincronização do BlueXP 

Para pagar antecipadamente pelas relações de sincronização, você deve comprar uma ou mais licenças e adicioná-las ao serviço de cópia e sincronização do BlueXP .

.O que você vai precisar
Você precisará do número de série da sua licença e do nome de usuário e senha da conta do site de suporte da NetApp à qual a licença está associada.

.Passos
. Compre uma licença por mailto:ng-cloudsync-Contact at NetApp.com?subject: Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[contactar o NetApp].
. No menu de navegação BlueXP , selecione *Mobilidade > Copiar e sincronizar*.
. Selecione *Licenciamento*.
. Selecione *Adicionar licença* e adicione as informações necessárias:
+
.. Introduza o número de série.
.. Selecione a conta do site de suporte da NetApp associada à licença que você está adicionando:
+
*** Se a sua conta já tiver sido adicionada ao BlueXP , selecione-a na lista suspensa.
*** Se a sua conta ainda não foi adicionada, selecione *Adicionar credenciais NSS*, introduza o nome de utilizador e a palavra-passe, selecione *Registar* e, em seguida, selecione-a na lista pendente.


.. Selecione *Adicionar*.






== Atualizar uma licença

Se você estendeu uma licença de cópia e sincronização do BlueXP  que adquiriu do NetApp, a nova data de expiração não será atualizada automaticamente na cópia e sincronização do BlueXP . Você precisa adicionar a licença novamente para atualizar a data de expiração. As licenças devem ser gerenciadas por meio da cópia e sincronização do BlueXP  ou do site aplicável e *não* por meio de uma carteira digital.

.Passos
. No menu de navegação BlueXP , selecione *Mobilidade > Copiar e sincronizar*.
. Selecione *Licenciamento*.
. Selecione *Adicionar licença* e adicione as informações necessárias:
+
.. Introduza o número de série.
.. Selecione a conta do site de suporte da NetApp associada à licença que você está adicionando.
.. Selecione *Adicionar*.




.Resultado
A cópia e sincronização do BlueXP  atualiza a licença existente com a nova data de expiração.
